/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarySystemManager;

import Database.ConnectionProvider;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Zak Andalion
 */
public class adminControls extends javax.swing.JFrame {

    /**
     * Creates new form adminControls
     */
    public adminControls() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setExtendedState(NORMAL);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Content = new javax.swing.JPanel();
        issueRecord = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        titleBar = new javax.swing.JPanel();
        exitBtn = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        toolPanel = new javax.swing.JPanel();
        titlePT1 = new javax.swing.JLabel();
        titlePT2 = new javax.swing.JLabel();
        borrowBookBtn = new javax.swing.JButton();
        viewBooksBtn = new javax.swing.JButton();
        issuedBooksBtn = new javax.swing.JButton();
        aboutBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        issuedBooksBtn1 = new javax.swing.JButton();
        backgroundTint = new javax.swing.JPanel();
        background = new javax.swing.JPanel();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        issueRecord.setViewportView(jTable2);

        titleBar.setBackground(new java.awt.Color(51, 102, 0));
        titleBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));
        exitBtn.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 20)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitBtn.setText("X");
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
        });
        titleBar.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 0, 40, 40));

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setFont(new java.awt.Font("Franklin Gothic Book", 1, 15)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Home Page");
        titleBar.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, 40));

        toolPanel.setBackground(new java.awt.Color(43, 47, 58));

        titlePT1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 35)); // NOI18N
        titlePT1.setForeground(new java.awt.Color(255, 255, 255));
        titlePT1.setText("Library ");

        titlePT2.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 35)); // NOI18N
        titlePT2.setForeground(new java.awt.Color(255, 255, 255));
        titlePT2.setText("Management Tools");

        borrowBookBtn.setBackground(new java.awt.Color(66, 71, 86));
        borrowBookBtn.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        borrowBookBtn.setForeground(new java.awt.Color(0, 0, 0));
        borrowBookBtn.setText("Borrow Book");
        borrowBookBtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        borrowBookBtn.setPreferredSize(new java.awt.Dimension(100, 30));
        borrowBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowBookBtnActionPerformed(evt);
            }
        });

        viewBooksBtn.setBackground(new java.awt.Color(66, 71, 86));
        viewBooksBtn.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        viewBooksBtn.setForeground(new java.awt.Color(0, 0, 0));
        viewBooksBtn.setText("View Book List");
        viewBooksBtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        viewBooksBtn.setPreferredSize(new java.awt.Dimension(100, 30));
        viewBooksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBooksBtnActionPerformed(evt);
            }
        });

        issuedBooksBtn.setBackground(new java.awt.Color(66, 71, 86));
        issuedBooksBtn.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        issuedBooksBtn.setForeground(new java.awt.Color(0, 0, 0));
        issuedBooksBtn.setText("Borrowed Books");
        issuedBooksBtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        issuedBooksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuedBooksBtnActionPerformed(evt);
            }
        });

        aboutBtn.setBackground(new java.awt.Color(66, 71, 86));
        aboutBtn.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        aboutBtn.setForeground(new java.awt.Color(0, 0, 0));
        aboutBtn.setText("About");
        aboutBtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        aboutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutBtnActionPerformed(evt);
            }
        });

        logOutBtn.setBackground(new java.awt.Color(66, 71, 86));
        logOutBtn.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        logOutBtn.setForeground(new java.awt.Color(0, 0, 0));
        logOutBtn.setText("Logout");
        logOutBtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });

        issuedBooksBtn1.setBackground(new java.awt.Color(66, 71, 86));
        issuedBooksBtn1.setFont(new java.awt.Font("Franklin Gothic Book", 0, 18)); // NOI18N
        issuedBooksBtn1.setForeground(new java.awt.Color(0, 0, 0));
        issuedBooksBtn1.setText("Registered Students");
        issuedBooksBtn1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        issuedBooksBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuedBooksBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout toolPanelLayout = new javax.swing.GroupLayout(toolPanel);
        toolPanel.setLayout(toolPanelLayout);
        toolPanelLayout.setHorizontalGroup(
            toolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolPanelLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(toolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toolPanelLayout.createSequentialGroup()
                        .addGroup(toolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(viewBooksBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(borrowBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(issuedBooksBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(issuedBooksBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aboutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toolPanelLayout.createSequentialGroup()
                        .addGroup(toolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titlePT1)
                            .addComponent(titlePT2))
                        .addGap(21, 21, 21))))
        );
        toolPanelLayout.setVerticalGroup(
            toolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolPanelLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(titlePT1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titlePT2)
                .addGap(18, 18, 18)
                .addComponent(borrowBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewBooksBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(issuedBooksBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(issuedBooksBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(aboutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ContentLayout = new javax.swing.GroupLayout(Content);
        Content.setLayout(ContentLayout);
        ContentLayout.setHorizontalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
            .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ContentLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(titleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(ContentLayout.createSequentialGroup()
                            .addGap(430, 430, 430)
                            .addComponent(issueRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(toolPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        ContentLayout.setVerticalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 764, Short.MAX_VALUE)
            .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ContentLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ContentLayout.createSequentialGroup()
                            .addComponent(titleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(issueRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(toolPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(Content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 700));

        backgroundTint.setBackground(new Color (255,255,255,200));

        javax.swing.GroupLayout backgroundTintLayout = new javax.swing.GroupLayout(backgroundTint);
        backgroundTint.setLayout(backgroundTintLayout);
        backgroundTintLayout.setHorizontalGroup(
            backgroundTintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        backgroundTintLayout.setVerticalGroup(
            backgroundTintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        getContentPane().add(backgroundTint, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 700));

        background.setLayout(null);

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Background/LogInPlaceholderBackground.jpg"))); // NOI18N
        background.add(backgroundImage);
        backgroundImage.setBounds(580, 0, 624, 700);

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        super.dispose();
    }//GEN-LAST:event_exitBtnMouseClicked

    private void borrowBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowBookBtnActionPerformed
        new borrowBook().setVisible(true);
    }//GEN-LAST:event_borrowBookBtnActionPerformed

    private void viewBooksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBooksBtnActionPerformed
        new bookList().setVisible(true);
    }//GEN-LAST:event_viewBooksBtnActionPerformed

    private void issuedBooksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuedBooksBtnActionPerformed
        new adminBorrowedControls().setVisible(true);
    }//GEN-LAST:event_issuedBooksBtnActionPerformed

    private void aboutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutBtnActionPerformed
        new about().setVisible(true);
    }//GEN-LAST:event_aboutBtnActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        super.dispose();
        new logIn().setVisible(true);
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void issuedBooksBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuedBooksBtn1ActionPerformed
        new registeredStudents().setVisible(true);
    }//GEN-LAST:event_issuedBooksBtn1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select borrowedBookList.studentId, studentRegistered.name, borrowedBookList.bookId, "
                    + "defaultBookList.bookTitle, borrowedBookList.issueDate, borrowedBookList.dueDate, borrowedBookList.returnedBook"
                    + " from studentRegistered inner join defaultBookList inner join borrowedBookList where defaultBookList.bookId = "
                    + "borrowedBookList.bookId and studentRegistered.id = borrowedBookList.studentID");
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Connection Error");
        }
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminControls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminControls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminControls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminControls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new adminControls().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JButton aboutBtn;
    private javax.swing.JPanel background;
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JPanel backgroundTint;
    private javax.swing.JButton borrowBookBtn;
    private javax.swing.JLabel exitBtn;
    private javax.swing.JScrollPane issueRecord;
    private javax.swing.JButton issuedBooksBtn;
    private javax.swing.JButton issuedBooksBtn1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JLabel title;
    private javax.swing.JPanel titleBar;
    private javax.swing.JLabel titlePT1;
    private javax.swing.JLabel titlePT2;
    private javax.swing.JPanel toolPanel;
    private javax.swing.JButton viewBooksBtn;
    // End of variables declaration//GEN-END:variables
}
